Header section
28919926/Portfolio1 pull request #1
Opened 2022-10-27 14:04 UTC by 28919926

- Add  html and css files
- Add the header section and content with corresponding styles on css.
- Fix errors on css.
- Add GitHub folder and linters files.
- Run and fix linters error.

2022-10-27 15:15 UTC, Abenezer-Tilahun requested changes
Hi @28919926 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct GitHub Flow.
✔️ Professional  README 
✔️ Good commit messages

![almost](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Required Changes ♻️

_Check the comments below the review._

## Optional suggestions

- [ ] Kindly Fix the MIT License in your README, The link is broken.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 15:15 UTC, Abenezer-Tilahun commented on style.css
> +}
- [x] As stated in the project requirement for "Headline section" you should use Flexbox in order to lay out the elements on the page and to make it's responsive,. Kindly Fix it.
![Capture](https://user-images.githubusercontent.com/93598189/198324975-a7886ae5-cd2b-41c5-92d8-51faec05c703.PNG)

2022-10-27 15:15 UTC, Abenezer-Tilahun commented on index.html
> +        <button type="button" class="collabo">Start collaboration</button>
- [x] As stated in the project requirement I recommend you to Implement the button interactions  styling: Active, Hover and Pressed ( Just Like the design).

![Capture](https://user-images.githubusercontent.com/93598189/198326189-6150534f-6602-46c6-a35c-c0f4ff782f11.PNG)

2022-10-27 15:15 UTC, Abenezer-Tilahun commented on index.html
> +    </section>
- [ ] As stated in the project requirement You must stick to the design as much as possible (e.g. font, colors, images, text, margins) using [the templates in Figma](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1). Kindly Adjust margin(bottom) for "Headline section" as defined in the design.

Your Project Look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/198328019-a64bfa55-5508-404b-abb9-765eaa63e5c6.PNG)

The Figma design Look likes this : 
![Capture](https://user-images.githubusercontent.com/93598189/198328531-c862e13f-fda2-4951-a935-e91b7aaefede.PNG)

2022-10-28 07:08 UTC, christianbiring1 requested changes
Hi @28919926 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

# STATUS: REQUEST CHANGES :recycle: 
![soclose](https://user-images.githubusercontent.com/97100091/198524989-c6600ddb-a2f3-4bef-8b1d-c1341bf6b611.gif)

 ## Highlights
- [ ] All linters checks are green :heavy_check_mark: 
- [ ] Descritpve PR `title` and `summary`

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 07:08 UTC, christianbiring1 commented on README.md
[OPTIONAL]
- [ ] It would be very nice to show how? with commands.

2022-10-28 07:08 UTC, christianbiring1 commented on index.html
> +            Wanjala</h1>
- [ ] As said by the previous reviewer, kindly make sure you stick to the design as much as possible. Your page and the template have to look similar.
Kindly make sure you have these images on your design.
Your design :point_down: 
![Screenshot from 2022-10-28 08-58-28](https://user-images.githubusercontent.com/97100091/198524156-ee43eac8-f72b-4601-ac8b-583b00373014.png)

Figma template :point_down: 
![Screenshot from 2022-10-28 09-03-08](https://user-images.githubusercontent.com/97100091/198524529-ffe83364-9c7f-4df1-b52a-c407940f5884.png)

![Screenshot from 2022-10-28 09-04-44](https://user-images.githubusercontent.com/97100091/198524700-f1dee89e-ad9f-4263-99ba-63857a39664f.png)

2022-10-28 09:26 UTC, OyePriscilla requested changes
Hi @28919926 😄 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. You can do it 👍 

![so-close-so-close-seth-meyers](https://user-images.githubusercontent.com/103386183/196425724-8ca5825c-b02a-4983-b976-4bd0a2f70f9a.gif)

 ## Highlights
✔️ No linter errors.
✔️ You used correct GitHub Flow.
✔️ Professional README
✔️ Good commit messages

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 09:26 UTC, OyePriscilla commented on index.html
> +        <img  class="imaghead" src="/images/headline.svg" alt="">
- [ ] KIndly place this image properly as the previous reviewers had noted. 😄 

## Your Design
![crr13](https://user-images.githubusercontent.com/103386183/198553271-5be1afbc-10b7-41c1-9a04-07307b573351.png)


## Figma Design 

![crr12](https://user-images.githubusercontent.com/103386183/198553378-d83e7705-909c-4d19-a9cb-c1ab7f65f56d.png)


- [ ] [optional] I am sorry that no reviewer mentioned this, the image should have been placed with CSS background property. 👍

2022-10-28 10:25 UTC, fobadara approved these changes
Hi @28919926, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Linters are passing
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 10:35 UTC, merged